### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by riya-17** [mhwkb/mhwkb.github.io#10]
Its front-end need improvement.

**Comment by andy5995** [comment]
Hi, @riya-17 

You are right! We are working on deploying Jekyll and working on the end-user experience. Thanks for your feedback. :)

Can I ping you in a few days to get more feedback from you?

**Comment by riya-17** [comment]
@andy5995 yes sure, can i contribute for front-end?

**Comment by andy5995** [comment]
Yes, that would be great! If you touch base with erichoog in our [Slack workspace](https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI) we can plan ahead a little.

Thank you!

**Comment by andy5995** [comment]
@riya-17 You can make some changes if you're still interested, but please don't do anything with the tags yet. I promised @nealkarpe he could work on them (mhwkb/mhwkb#126)

https://github.com/mhwkb/mhwkb.github.io/wiki/Testing

I haven't decided yet what's going to be on the home page, so just work around that for now.

**Comment by andy5995** [comment]
This ticket is open, afaik. I haven't heard back from @riya-17 .

**Comment by riya-17** [comment]
@andy5995 ok i will try my best to improve home page.

**Comment by andy5995** [comment]
Oh, @riya-17 wb! If you ever need extra time, feel free to let me know. Sometimes I don't know if someone has permanently left or just needs extra time. :)

**Comment by andy5995** [comment]
This is the graphic we'll be using. We had thought to put it at the top of the page next to the title.

https://github.com/mhwkb/mhwkb.github.io/blob/master/images/mhwkb_dharma_wheel_logo_406x384.png

**Comment by andy5995** [comment]
Yes. I think we  might need to adjust the size though. What do you think?

**Comment by riya-17** [comment]
left-top corner is best for logo, it is just like an ideaL place. @andy5995

**Comment by andy5995** [comment]
Closing. Making tickets for for different tasks.
