### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by afro-nolan** [mhwkb/mhwkb.github.io#105]
In order to make the page more inviting and therefore to raise further awareness by drawing readers in, I would suggest adding some images with the links or articles, it would make the website a lot more user-friendly and easier to navigate.

**Comment by andy5995** [comment]
Thank you for the suggestion. What difficulties did you have with navigation? What kind of images do you suggest adding? What was your experience that you didn't find the site user-friendly?

**Comment by afro-nolan** [comment]
I found that the links where somewhat vague in what they were about and almost had the appearance of clickbait of spam, I had a look at a few of them though and it seems that a majority of them are links to articles so it could be an interesting idea to include a picture along with the link that would relate to the articles/ webpage to give a glimpse of what the content is about. It shouldn't be too hard to do, just just a matter of including it in the css and html. The main issue I had with appearance and usability was the readability and formatting of the links.

**Comment by andy5995** [comment]
>had the appearance of clickbait of spam

Hmm.. that's good feedback. I wasn't aware of that point of view. I'll leave this ticket open for more discussion.

My concern about adding pictures is copyright of course.

The primary reason the site is mostly just links is because though I wanted to help with awareness, I didn't want to maintain a big project for an indefinite period of time. I'm really more interested in C programming than web development. In fact the majority of the work here (esp. CSS, HTML, and jekyll configurations) has been done by contributors.

But we definitely want to make clear what the site is about, and I'm glad you gave us an account of your objective experience.

How did you find the site originally? Through a search engine or a Github profile..?

**Comment by erichoog** [comment]
I've never used anything like this but this code might be something to look at maybe?  Essentially a way to show a thumbnail of the website using the link I beleive: https://html2canvas.hertzen.com/documentation.html

**Comment by JedMeister** [comment]
I quite like the idea of a thumbnail of the website the link is to. 

@andy5995 - re your concerns on copyright, if you keep in context that by providing a link to their site, the KB is improving their SEO and driving traffic to their site (at no cost to them). I would argue that under US DCMA ["fair use"](https://www.dmca.com/FAQ/Fair-Use) provisions, it's totally reasonable to give KB users an idea of what they'll see when they click. 

If you are still concerned about it, perhaps it'd be worth including a 'legal' page which spells out a DCMA takedown process? Actually GitHub already have a pretty extensive process, so while the site remains hosted on GitHub, perhaps the project could just leverage that? FWIW, here are some links related to GH policy and process:

https://help.github.com/articles/dmca-takedown-policy/
https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/
https://github.com/contact/dmca
https://github.com/contact/dmca-notice

**Comment by andy5995** [comment]
Thanks for all the legal info @JedMeister .  If anyone wants to try implementing this, I'm fine with that.

**Comment by DRD161** [comment]
I would like to take on this issue. I know that copyright is an issue, Unsplash.com offers thousands of images that are free to use so I'm sure that this would be easily do able.

**Comment by andy5995** [comment]
@DRD161 thanks for the info, but there's no code yet to actually display any pictures, nor any method decided upon for implementation.

**Comment by DRD161** [comment]
I could write the code no problem. There are a few ways it could be done using CSS. If we could come to an agreed upon way to implement this I could start on it. Whatever I can do to help out :)

**Comment by andy5995** [comment]
Sounds good! Our Slack workspace is a good place to discuss such things, and you're welcome to join.

**Comment by DRD161** [comment]
@andy5995 Ok awesome, what's the slack dev group name? I'll check that out tonight.

**Comment by andy5995** [comment]
https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI

**Comment by DRD161** [comment]
@andy5995 I'm trying to type in the source path for images but they are not displaying on the page. I keep seeing a broken image link with any image I try. I am storing my images in the image directory. I see that the images that are already on the page have an image source of https://mhwkb.github.io/images/insert_image_here. Are all of the images being stored elsewhere? Using the absolute path or relative path has not worked for me thus far. Any idea what I may be missing?

**Comment by erichoog** [comment]
@DRD161 what specific images folder are you using? The images need to go under `jekyll/images`

The other thing to check would be the path you're referencing in HTML it should look something like this:

`<img src="{{ site.url }}/images/mhwkb_dharma_wheel_logo_180x170.png">`

**Comment by DRD161** [comment]
@erichoog Ok I think I see the problem I was using the image folder that was NOT in the jekyll folder. But even when my image is int the jekyll/images folder and the path is this: https://mhwkb.github.io/images/nature.jpg" the image still shows a broken link icon

**Comment by DRD161** [comment]
@erichoog So my issue was with a ruby dpenedancy of some sort. BUT now when I follow the steps to run jekyll by doing bundle install withing the jekyll directory I get this error in the command line:

/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'

then I try and run the jekyll server anyways using bin/run-jekyll I get this error:

== Starting jekyll server ==
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'

**Comment by DRD161** [comment]
I've been looking online for about an hour and have not found a viable solution. I'm using Ubuntu 16.04.4 LTS if that helps any. Also, I have joined the Slack channel if that makes any further communication easier.

**Comment by andy5995** [comment]
@DRD161 is working on this in #133
