### ISSUE TITLE
when running locally, some links not showing up in search

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#106]
Some links not showing up in search when running jekyll locally.

I don't know how many  links are not showing up in the search, but this is one post that's not coming up in  the results.

```
---
layout: post
title: "mental-health-resources"
href: https://github.com/agelender/mental-health-resources
date: 2017-11-04 01:16:34 +0000
tags: ["GitHub", "directory", "crisis", "suicide prevention"]
categories: EN
---
```

**Comment by erichoog** [comment]
Hey Andy, I just checked this locally here. It seems the like shows up for me after I type `menta` in.  But if I only have 'ment' typed then it doesn't.  Is it similar for you or just doesn't show up at all.

**Comment by andy5995** [comment]
It doesn't show up at all.

**Comment by erichoog** [comment]
Hmm can you check the browser console (usually F12 or Ctrl+Shirt+K in Firefox) and see if there's any errors showing up that might be related? Unless you've already done that.  If there's no errors tied to that then I'd have to check it out again but I can't see any reason it wouldn't.

**Comment by andy5995** [comment]
>Hmm can you check the browser console (usually F12 or Ctrl+Shirt+K in Firefox)

Ok. I don't know how to use the console, but I don't see anything that looks like an error. I see some orange triangles with exclamation marks next to these.

```
html {
    font-size: 10px;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
html {
    font-family: sans-serif;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;

```

**Comment by erichoog** [comment]
Hey @andy5995 make sure you're on the Console tab as shown below, I feel like you might be on the Inspector tab.

It should look something like this:

![image](https://user-images.githubusercontent.com/8869330/33150687-9726aab4-cfa2-11e7-8cfc-84bbd54d375b.png)

> Note: this error only shows up on the home page, so if there's nothing listed then that's a good thing!

**Comment by andy5995** [comment]
Ah.. ok. I do get that error when in the console at the home page. When using the search, the console window is blank.

**Comment by erichoog** [comment]
Ok that's good at least.   Have you tried typing that title out fully and see if it shows up?

**Comment by andy5995** [comment]
oh, yes it does now. I'm sure I tried that before and it didn't work. Great! You fixed things again! hehe

**Comment by erichoog** [comment]
Perfect!  I noticed I has to type it out almost fully before I saw it in the list as well.
