### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by ritwik12** [mhwkb/mhwkb.github.io#116]
When I saw this website I noticed a problem, for the people who doesn't have any idea with other languages it is hard to know that which short form is which language.
Like
EN-english DE HI-Hindi NL SV NE pt_BR
But I don't have any idea about others without clicking on them.
So I thought there is a need for Tooltips

**Comment by andy5995** [comment]
@ritwik12 Thank you for the suggestion. :) This is part of #35

**Comment by ritwik12** [comment]
@andy5995  alright
