### ISSUE TITLE
Width of language navigation drop-down needs to be expanded

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#119]
It's too narrow!

**Comment by robatronPrime** [comment]
Hi, I can do this for you. How wide do you need it?

**Comment by andy5995** [comment]
Thanks for the offer @robatronPrime . I think it should be wide enough so the language names can be read. In my browser, I'm seeing "Nederl..." and "Portug..." among the languages.

**Comment by robatronPrime** [comment]
What browser are you getting these problems?

**Comment by erichoog** [comment]
@andy5995 I'm also not seeing this issue on Firefox for linux or android, what browser are you using?

**Comment by erichoog** [comment]
@andy5995 upon further review I do still see this issue, for Nederlands.  I'll take a look
