### ISSUE TITLE
Fix footer layout

### ISSUE THREAD

**Issue by erichoog** [mhwkb/mhwkb.github.io#126]
I've noticed on mobile that the layout of the footer doesn't quite look right.

Half of it seems to sit higher than the other half.

Here's a screenshot I'm using Firefox on Android:

![screenshot_20180120-211208](https://user-images.githubusercontent.com/8869330/35190055-a718e556-fe26-11e7-9c1d-b26ddb12bb5c.png)

**Comment by andy5995** [comment]
labelled and accepted ;)
