### ISSUE TITLE
Link suggestion -

### ISSUE THREAD

**Issue by lamlilom** [mhwkb/mhwkb.github.io#137]
To suggest a link for the Knowledge Base, please fill add a title above,<br />
and fill out the form below.<br />
(if filing a regular issue, press `<CTRL-a>`, followed by a backspace)

Link title:

URL:

Up to 10 keywords or tags (spaces ok), one per line:

If you'd like to add this link to the KB, details on how to do so are at
https://github.com/
mhwkb/mhwkb.github.io/issues/11

If not, just hit _submit_ after you enter in the link details. Thank
you!

**Comment by andy5995** [comment]
Issue template not filled out. closing..
