### ISSUE TITLE
code on the home page needs proper indentation

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#14]
https://github.com/mhwkb/mhwkb.github.io/blob/f1646ce02b72c094456edbee6a92245b9f6a26d8/jekyll/_layouts/home.html#L16

4 space indentation

**Comment by kcamacho1** [comment]
Hello, I would like to resolve this issue for you but I am having trouble locating the Homepage file to edit. Can you assist so I can make the pull request?

Thank you.

**Comment by andy5995** [comment]
@kcamacho1 Someone already took care of that, but could you remove the id, class, and style attributes from these 3 tags?

```
 <span id="ctl00_PlaceHolderMain_DisplayNewsID_lblNewsFullText" class="lblnewsfulltext" style="display:inline-block;width:100%;">
<div class="ExternalClass4C9C8280F0EA4A2C9B9780FDF91D4465">
```

https://github.com/mhwkb/mhwkb.github.io/blob/bdc36638bef9539793e913580ed6595f5be1fcba/jekyll/_layouts/home.html#L18

**Comment by andy5995** [comment]
@kcamacho1 You will need to sync your fork first.

https://github.com/mhwkb/mhwkb.github.io/blob/master/CONTRIBUTING.md#syncing

**Comment by andy5995** [comment]
>but could you remove the id, class, and style attributes from these 3 tags?

@erichoog took care of that (#19, f658005bfd49a31d0aafc8d6a901527320a2263c)

**Comment by erichoog** [comment]
@andy5995 I think it might still be in there

**Comment by andy5995** [comment]
that issue covered in #19 now
