### ISSUE TITLE
add validator button to the bottom of the site

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#140]
This code to add a w3 validator button should be added to the bottom of the site

```
  <p>
    <a href="https://validator.w3.org/check?uri=referer"><img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0!" height="31" width="88" /></a>
</p>
```

**Comment by danielmitre** [comment]
Where exactly it should be? Maybe under permalinks section?

**Comment by andy5995** [comment]
Yes, that sounds good. Centered at the bottom. Thank you.

**Comment by shubhamcr** [comment]
I am working on it.

**Comment by andy5995** [comment]
@shubhamcr, you'll need to let @danielmitre take the first shot at it.

**Comment by shubhamcr** [comment]
OK.

**Comment by andy5995** [comment]
completed by @danielmitre in https://github.com/mhwkb/mhwkb.github.io/commit/5c7b529637ab9e89a4ffd8501f8b6ff6288bb723
