### ISSUE TITLE
Add style to the "edit this entry" post link

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#162]
The "edit this entry" link isn't live yet, but the code changes are in the jekyll branch.

![image](https://user-images.githubusercontent.com/16764864/47677718-e09c2000-db8d-11e8-8cb3-361de0e3c4fb.png)

The link could use a bit of style though.

**Comment by babzcraig** [comment]
Hi @andy5995 I'd like to take this up to get my feet wet. Is that okay?

**Comment by andy5995** [comment]
Yes, @babzcraig

**Comment by babzcraig** [comment]
Got it. I'm on it

**Comment by andy5995** [comment]
Completed by @babzcraig in #164
