### ISSUE TITLE
jekyll-paginate update breaks jekyll build

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#167]
The [jekyll-paginate plugin](https://github.com/jekyll/jekyll-paginate) is no longer under active development (according to a statement at the top of its repo). When I tried updating to the latest release, it breaks the jekyll build:

```
Using jekyll-feed 0.11.0
Fetching jekyll-paginate-v2 2.1.0 (was 2.0.0)
Installing jekyll-paginate-v2 2.1.0 (was 2.0.0)
Bundle updated!
andy@oceanus:~/src/mhkb/mhwkb.github.io$ jekyll serve
Configuration file: /home/andy/src/mhkb/mhwkb.github.io/_config.yml
            Source: /home/andy/src/mhkb/mhwkb.github.io
       Destination: /home/andy/src/mhkb/mhwkb.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Generating tags pages
         AutoPages: categories pages are disabled/not configured in site.config.
         AutoPages: collections pages are disabled/not configured in site.config.
  Pagination Error: Detected invalid url "/category/DE/alphabetical" for "category/DE_alphabetical.html"
                    Expected "/category/DE/" or "/category/DE/index.html"
```

Dunno of we could keep the plugin at v2.0.0 forever or look at using an alternative at some point, or try using [jekyll's internal paginate feature](https://jekyllrb.com/docs/pagination/) again.

**Comment by erichoog** [comment]
I think we could switch to the default Jekyll paginate feature but it will likely break some things (which I'd need to refresh myself on).

The other option is to read in the markdown data and convert it to json similar to what the up for grabs.net site does.  

Not sure I'd be able to work on this anytime soon tho

**Comment by andy5995** [comment]
Hi @erichoog  :)

I'm not in any hurry. May be better to archive and deprecate this project and use some entirely different platform. Though I don't know who would want to set it up, lol. 

Take care...

**Comment by andy5995** [comment]
There's been some active development on paginate-v2.. It's now at 3.0.0 ;)

https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0

I upgraded Jekyll from 3 to 4 and all dependencies and debts have been paid. :)
