### ISSUE TITLE
when clicked from the rss feed, links in posts don't display

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#17]
https://github.com/mhwkb/mhwkb.github.io/blob/069c3fc00b2aae7a4661c9610ad8ee611f06501d/jekyll/_includes/post_display.html#L7

When clicked from the rss feed, links in posts don't display

Page comes up without the link title or tags. Not sure why this is happening yet.

Viewing the source, I see
```
 <p><a href=""></a></p>
```

Why the info isn't getting passed, I don't know. The _include file used to display the post is  the same file that displays the posts on the other pages of the site.

**Comment by erichoog** [comment]
Ok so the RSS feed appears to be showing posts outside of the category, it's showing the actual post page I beleive, as the links are going to `https://mhwkb.github.io/en/2017/11/04/Men_how_to_have_a_conversation_with_a_mate_about_mental_health/`

**Comment by andy5995** [comment]
fixed by https://github.com/mhwkb/mhwkb.github.io/commit/d942010e5134620f2c2b79ff2b59090345b74a0e Thanks @erichoog

**Comment by erichoog** [comment]
Whoops, meant to include (Closes #17)  in the title of the PR, thought solves worked as well but my bad!
