### ISSUE TITLE
home page doesn't validate

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#19]
Warnings and error when validating

https://validator.w3.org/nu/?doc=https%3A%2F%2Fmhwkb.github.io%2F

https://github.com/mhwkb/mhwkb.github.io/blob/c2d603e67949a1f45fcad656200bd11c35c1e923/jekyll/_layouts/home.html#L19

**Comment by erichoog** [comment]
still more to fix

**Comment by andy5995** [comment]
Now I think it's better to wait on this until @riya-17 adds some design. Thanks for following up.

**Comment by erichoog** [comment]
@andy5995 all W3 validation passing now.
