### ISSUE TITLE
write a program that will generate jeykll posts

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#26]
write a program that will generate jeykll posts

Here's what the output file would look like:

```
---
layout: post
title: "Side Effects: A Prosecutor, a Whistleblower, and a Bestselling Antidepressant on Trial"
href: http://a.co/0BuSDiT
date:   2017-10-28 12:00:00 -0500
tags: [books, Alison Bass, journalism, side effects, conflicts-of-interest]
categories: EN
---
```

This program can be in any language. Here's what it should do:

The config file will contain the desired fields.. a comma separated list perhaps..

`# fields`
title, href, date, tags, categories

The program run from the terminal, it should prompt for each field found in the config

title? 
href?
tags?
categories?

The filename written would be preceded by  YYYY-MM-DD- and the rest would be the title entered in at the first prompt. Spaces converted to underscores, and any characters that aren't allowed in filenames stripped away.

(see https://github.com/mhwkb/mhwkb.github.io/tree/master/jekyll/_posts/EN for a listing of current files)

The date field within the post can use the current date, must match the format

The output file can just appear in the present working directory.

It may be good to start your own GitHub repo for this project. After the program is found to work reliably, it would be added to a separate folder here, along with a README and credits to yourself and your repo.

**Comment by andy5995** [comment]
Eric's working on this: https://github.com/erichoog/jekyllpostgen

**Comment by luiemilio** [comment]
I did one for practice
https://github.com/luiemilio/jekyll_post_generator

Sorry for not saying anything before doing it.

**Comment by erichoog** [comment]
@andy5995 @luiemilio no worries you can use that one! I might keep working on my version just for fun anyways!

**Comment by andy5995** [comment]
@luiemilio  Thank you.

If you like, you can do a PR and put it in a directory here as the same name as your project.

I tried running it

```
./jekyll_gen.rb: line 1: class: command not found
./jekyll_gen.rb: line 2: syntax error near unexpected token `('
./jekyll_gen.rb: line 2: `  def initialize(config_file)'
```

Adding this to the first line solved it

`#!/usr/bin/env ruby`

Works pretty well!

```
andy@oceanus:~/src/jekyll_post_generator$ ./jekyll_gen.rbtitle?
hellow world
href?
http://google.com
tags?
hello, howe are you, I am fine  
categories?
EN
```

Works pretty well!

```
layout: post
title: hellow world
href: http://google.com
date: 2017-11-01 22:11:41 +0000
tags: [hello, howe are you, I am fine]
categories: EN
```

Can you have it make double quotes around the "title"? And add the three dashes, as shown in the example in the first post?

Wow, this is going to save a lot of time! Thank you @luiemilio !

**Comment by andy5995** [comment]
One of these was done by @luiemilio and @erichoog is working on another,

Show your love and "star" their projects!

https://github.com/erichoog/jekyllpostgen

https://github.com/luiemilio/jekyll_post_generator

If anyone makes another one, please do a PR and I'll review and probably add it to our repo. Please include a LICENSE for your project, and the README, which should link back to your project page. A note in the README saying something like, "Any PRs for this generator should be made at `<repo URL>`
