### ISSUE TITLE
pagination works on category pages but not on tag pages

### ISSUE THREAD

**Issue by riya-17** [mhwkb/mhwkb.github.io#31]
As it consists of a long list of hyperlinks so it will be better to divide them into different pages like google and arrange them alphabetically.Instead of arranging we can give sortings like sort by date or sort by name where pagination is still required.

**Comment by andy5995** [comment]
Thanks for filing this @riya-17 .

We put deployed the new site yesterday, and now the links aren't in a very long list such as you described.

https://mhwkb.github.io/

Though we are still having some issues to solve.

1. pagination works on category pages but not on tag pages
2. We only have next (older) and previous (newer) links for the pagination, not <prev 1 2 3 5 6 7 8...

Definitely both of these issues we'd like fixed.

As for arranging them alphabetically... Definitely a good option to have. I'll create a ticket for that.

**Comment by andy5995** [comment]
I'm pretty sure this done. Thanks @erichoog :) (https://github.com/mhwkb/mhwkb.github.io/commit/0139ca7db4cb6a42b537b0a6a75f65991c307705)

The alphabetizing thing mentioned above is now in a separate ticket #33

**Comment by andy5995** [comment]
>pagination works on category pages but not on tag pages

Oh, I may have closed this ticket prematurely. renamed title and reopening....
