### ISSUE TITLE
sorting posts alphabetically

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#33]
As @riya-17 pointed out in #31, there should be an option to sort posts alphabetically.

That would be a bit more challenging because the site is hosted on [GitHub Pages](https://help.github.com/articles/what-is-github-pages/).

>GitHub Pages is a static site hosting service and doesn't support server-side code such as, PHP, Ruby, or Python.

So, as far as we know.. we have no database capability unless someone wants to register a domain, buy hosting, and maintain it over an indefinite period of time. ;)

However, if there is a way, we will figure it out.

@erichoog This might be a case where chaining _config files would come in useful. I haven't reasoned it all out yet, but I'm thinking one _config file sorts the posts alphabetically, puts them in different dirs at the ones sorted by date. A link on a category language page -> Sort by name, which then loads the index of paginated pages that are sorted by name.

One minor disadvantage is that there would be twice as many pages on the server.

**Comment by riya-17** [comment]
Pagination seems to be Perfect now.

**Comment by andy5995** [comment]
Thanks @riya 😃

**Comment by erichoog** [comment]
I think using Javascript would be the most practical way to enable, sorting and filtering.  I've looked at how [up-for-grabs.net](https://up-for-grabs.net) implements this and i think that would be the best way.  But I'm yet to try it out for this site!

**Comment by andy5995** [comment]
Well.. you know me.. I don't know anything about Javascript.. But you sound like you know what you're talking about, lol.

Thanks for giving it some thought though. It surely does seem that up-for-grabs has everything all figured out, doesn't it? xD

**Comment by dreamingblackcat** [comment]
@andy5995 I've sent a [PR](https://github.com/mhwkb/mhwkb.github.io/pull/139) for this.
