### ISSUE TITLE
change style of category (language) links

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#35]
move category display to header

This needs to get moved (L4)

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_layouts/home.html#L4

and placed in

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_includes/header.html#L5

That will make sure the LANG buttons will show up on tag pages, as well as category pages.

Also if anyone feels the style could be improved upon, that could be part of this ticket.

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_includes/category_display.html#L10

This is our logo that @jamielthompson29 made.

https://github.com/mhwkb/mhwkb.github.io/blob/master/images/mhwkb_dharma_wheel_logo_406x384.png

So any new styles should not conflict with the color scheme of the logo.

**Comment by andy5995** [comment]
The first part is done, so I've renamed the ticket. Are we thinking drop-down box for the languages?

**Comment by riya-17** [comment]
A menu that open from sideways will be good or a menu icon that shows a dropdown will be good as well.

**Comment by riya-17** [comment]
Which will be an ideal place for menu icon?

**Comment by andy5995** [comment]
The top.

**Comment by andy5995** [comment]
This should be combined with #69 but perhaps 69 is no longer needed.

**Comment by andy5995** [comment]
I'm thinking something like this would be a good option.

http://bootstrapformhelpers.com/language/#example3

The code that auto-displays the categories can be removed and replaced with static links. We only have 5 languages right now and adding more is as simple as copying and pasting, and changing the country code.

https://github.com/mhwkb/mhwkb.github.io/blob/b23edaf8250605c90bdf5580245efa6b1e753d14/jekyll/_includes/category_display.html#L1-L14

**Comment by andy5995** [comment]
Closed by accident. I made some recent commits while on the wrong branch. (ping #94)
