### ISSUE TITLE
date can be removed, post link and title given style

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#37]
The display of the date can be removed, give style to post title and link.

https://github.com/mhwkb/mhwkb.github.io/blob/48ea1a5d6e2c5a030db495c7be6e05343fc7e1ba/jekyll/_includes/post_display.html#L5

**Comment by andy5995** [comment]
Tags can be part of this ticket also.

Colors don't have to necessarily match, but they should not conflict with our new logo.

https://github.com/mhwkb/mhwkb.github.io/blob/master/images/mhwkb_dharma_wheel_logo_406x384.png

**Comment by andy5995** [comment]
@nealkarpe can you take this ticket?

**Comment by nealkarpe** [comment]
Sure. I'll take this up! :smiley:

**Comment by nealkarpe** [comment]
Do you suggest that I should comment out the date if we may decide to use it again in the future? Or should I simply delete the date if you're sure you don't want it? (worst case we can re-track it from the commits either way :smiley: )

**Comment by andy5995** [comment]
Delete. :)

But don't delete from any files in the _posts directory. Still needed by Jekyll for sorting.

**Comment by nealkarpe** [comment]
Quick question. Seeing that we have no css file to write styles of classes, should I make one or do you suggest just writing styles independently in each individual file?

**Comment by andy5995** [comment]
I think @escottalexander is going to add a css file today.

In the meantime, you can use classes from Bootstrap https://github.com/mhwkb/mhwkb.github.io/blob/master/CONTRIBUTING.md#css-design-we-use-bootstrap

For example, you've seen this in our html documents:
`class="label label-danger"`

That's using the bootstrap code that's being linked to in `<head>`

If you have any questions about it, you can also pm me in Slack. That will help cut back on some of the emails to people who are "Watching" this project. :)

**Comment by escottalexander** [comment]
He had assigned me to create a style.css file. I am working on it currently and hopefully it will be available for you to edit soon.

**Comment by andy5995** [comment]
closed by d748d696ebfd0e9cf979d6686a087e73a7084486 Thanks @nealkarpe
