### ISSUE TITLE
placement and style of red footer buttons

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#48]
https://github.com/mhwkb/mhwkb.github.io/blob/5cff373c91970f9f5f5ab0ec32d356c3e20c5280/jekyll/_includes/footer.html#L6

A few minutes ago I updated the upstream to correct a couple links there. So before you work on this, you should definitely [sync](https://github.com/mhwkb/mhwkb.github.io/blob/master/CONTRIBUTING.md#syncing).

the style can change, as well as the colors.

I think we need an _About_ and _Home_ button at the top as well as the bottom. Either underneath the web site title, or above it. Express your creativity and show me some ideas if you feel like it. :)

The colors should associate well or not conflict with the new logo
https://github.com/mhwkb/mhwkb.github.io/blob/master/images/mhwkb_dharma_wheel_logo_406x384.png

**Comment by escottalexander** [comment]
@andy5995 Looking forward to working on this tomorrow. Thanks.
