### ISSUE TITLE
home page layout

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#5]
I figured the best way to do the home page is to have a brief intro/welcome message (TBD), with the language links prominently displayed.

## EN | DE | HI

Not necessarily using that style.

Reason being.. it seems that otherwise there would be a mix of different language links on the home page.

If there's any reasons something different should be discussed, please let me know.

**Comment by erichoog** [comment]
I would have to agree on this, I'll try to look into this a bit more.  There's likely a way to filter the list by category and can likely set one category as the default.

We could do something like having a dropdown list for switching the languages as well possibly.  If we list the languages in the format  "LANG1 | LANG2 | LANG3" etc - this list could get very long but it could be something we could work on later.

**Comment by erichoog** [comment]
Another idea may be to have a side bar menu with a list of the tags or a drop down for the tags rather than displaying them all for each article on the home page.  I'm still trying to get an idea of what the final product might look like.

**Comment by andy5995** [comment]
The language list could get long, but I don't see that happening for a very long time. But I wouldn't rule it out. At some point, a drop down would be fine, so long as search engines could still crawl those links. I've seen some code on wordpress blogs that appear to allow engines to crawl so I'm reasonably certain it could be done.

As for tags, not sure about a drop-down for them yet. Seems unlikely actually. There were about 160 total tags on the old site, and we've only just started adding links. I'm thinking just a separate page that lists all the tags used on the site. What do you think of that?

>rather than displaying them all for each article on the home page.

Hmm.. good point that maybe showing the tags like that is perhaps unneeded clutter. First thing that comes to my mind to solve that is having a box on each on that says "view tags", and when clicked, "unhides" the tags. I'd still want the tags link to be crawlable by search engines.

**Comment by riya-17** [comment]
i think arranging them on different pages with numbers like on google
search would be better rather than drop down or long scrolling

**Comment by andy5995** [comment]
@riya-17 yeah, we need pagination on tag pages. And the numbering system, you're absolutely right. Would you mind creating a ticket for that?

**Comment by andy5995** [comment]
I'm going to divide up the design tasks, and hopefully that will make thing easier to work on for everyone.

**Comment by riya-17** [comment]
Yaa that will surely make things easier.
