### ISSUE TITLE
implement navigation bar / drop-down box for tags

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#51]
Anyone interested in implementing a navigation bar / drop-down box for tags?

https://github.com/mhwkb/mhwkb.github.io/blob/431a8a90bb3515d2a9845457bacb466998696c88/jekyll/_includes/post_display.html#L8

**Comment by erichoog** [comment]
I'd be interested in implementing the initial navbar if no one else wants to later this evening.

Would need to clarify the drop down for the tags.  Is a drop down in the nav which would list out all of the tags on the page?

I could still implement the nav to show the concept I had been talking about and then we could work on the drop downs / modifications we'd need to do later.

**Comment by andy5995** [comment]
a drop-down just for the tags in a single article/link.

@escottalexander said he'd take this but was concerned about setting up Jekyll. Which is now done. :)

>I could still implement the nav to show the concept I had been talking about and then we could work on the drop downs / modifications we'd need to do later.

Sure, @erichoog if you're interested in doing that, I'll certainly have a look. :)

**Comment by escottalexander** [comment]
@erichoog If you want to work on this, go ahead. I will be away from my computer the rest of the night. If not, I'l check into it in the morning

**Comment by erichoog** [comment]
I made a quick attempt at implementing what I was talking about but I wasn't all that happy with it so I'll probably hold off on this until some inspiration comes.

**Comment by nealkarpe** [comment]
Hi! I saw the pull request and the work looks really neat! :smiley: Just wondering what is the motive of having the tags along with a drop-down of the same tags? However, this is just my opinion. If you feel that it is more usable with the drop-down, then no problems! Cheers :)

**Comment by andy5995** [comment]
>Just wondering what is the motive of having the tags along with a drop-down of the same tags?

#59 isn't finished yet, there will only be the drop down.
