### ISSUE TITLE
implementing a right-hand vertical panel

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#60]
I keep thinking we should have a vertical right-hand panel for some extra things, such as

* Features links (3-5 links that are visible on every page)
* Drop-down tag-cloud box
* move the three "add to the KB" links from the footer into the right-hand panel

**Comment by andy5995** [comment]
Are right-hand panels used anymore? @JedMeister will say I'm back in the nineties, lol. But seriously, I tried it today, but it seemed that if viewed on a mobile device, it just wouldn't work.

**Comment by erichoog** [comment]
I like the idea of having those links easily accessible but I agree that the panel wouldn't view nicely on a mobile device.  I wonder if we could use a bootstrap row and col from their grid system if it would work better?

**Comment by andy5995** [comment]
I may have missed this, @erichoog 

But now, 2 months later, I don't see that we have a lot of extra links, and the footer is holding things nicely.
