### ISSUE TITLE
implement htdig search engine

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#72]
We probably shouldn't spend too much time on this; if we don't get it working, we'll look at the other options mentioned in #63 

So, to test `htdig` the way I did, is pretty easy (if it's even something anyone wants to do. As I said, not mission-critial).

1. install htdig from your Linux distro repository.

The rest can be done as a normal user.

Copy the [config file](https://github.com/andy5995/htdig/blob/39c27f37c00645660db381927e95d96e6ca79240/installdir/htdig.conf#L1) to a directory you have permissions on.

Edit L18 to any temp directory you have write permissions on.
Edit L29 to a URL you want to try.

Run `htdig -c <path to config> -ivvs`

The `i' is to create the initial database. `s` gives statistics at the end. `vv` gives extra verbosity.

Here's the output of `htdig -ivvs` when I tell it to crawl http://localhost:4000

https://gist.github.com/andy5995/e80ef0b0ef5cde68e25fc075dce3ac11

the size of the database files it creates:

```
  88K Nov  8 20:01 db.docdb
  24K Nov  8 20:01 db.docs.index
 176K Nov  8 20:01 db.excerpts
162K Nov  8 20:01 db.words.db
  16K Nov  8 20:01 db.words.db_weakcmpr
```

When I tell it to crawl https://mhwkb.github.io

https://gist.github.com/andy5995/8fd45502a476c7579cb436a8dc950516

It seems to hang when crawling the EN category, but it eventually continues.

```
  24K Nov  8 20:07 db.docdb
  24K Nov  8 20:07 db.docs.index
 32K Nov  8 20:07 db.excerpts
 15K Nov  8 20:07 db.words.db
  16K Nov  8 20:04 db.words.db_weakcmpr
```

So obviously it's not doing much crawling of the actual live site. Seems to be likely that it's related to the ssl connection. Whether or not there's a workaround for it, or an easy fix, I don't know yet.

**Comment by andy5995** [comment]
Closing, search implemented with a062a59ec12c83d285cc3b3df11ff596319762b6

**Comment by andy5995** [comment]
@erichoog The problem has been fixed. I found this patch that was made in 2013, nine years after the last official release, and merged it with my repo.

https://github.com/andy5995/htdig/commit/2aa0e4ed52211003288491dedd3a1e72d1c4ddc1

**Comment by erichoog** [comment]
Oh nice that's awesome! Good job researching that!  I still haven't had a chance to try this out but hoping to eventually!
