### ISSUE TITLE
Some links to tag pages lead to a 404, problem with `- ` combination

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#73]
The tagging plugin usually handles tags with spaces ok.

In this example in the DE (German) category, it does not.

https://mhwkb.github.io/tag/kinder--und-jugendgesundheit/ (Leads to a 404)

The literal tag is
`Kinder- und Jugendgesundheit`

Looks like it has something to do with a hyphen being next to a space; and normally spaces are converted to hyphens. I see in tag page URL that there's only one hyphen, when there should be two.

That post was added by a native German speaker, by the way, and I'm pretty sure that's how it's supposed to be; with the `-` there. A close translation would be "child and adolescent health".

I see if I manually add the extra hyphen and paste the URL in to my browser, the tag page will show.

https://mhwkb.github.io/tag/kinder--und-jugendgesundheit/

**Comment by andy5995** [comment]
Some trouble with the Nepali tags too. If you click on this link you'll see it works, but all the tags around it lead to a 404.

https://mhwkb.github.io/tag/%E0%A4%94%E0%A4%B7%E0%A4%A7%E0%A4%BF/

**Comment by erichoog** [comment]
@andy5995 not sure why this didn't close automatically?

**Comment by andy5995** [comment]
It's a mystery to me, too.
