### ISSUE TITLE
Logo and title design

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#75]
Any ideas about how to present the logo and title on the home page page? Background colors? a subtle background image? Font, placement?

https://mhwkb.github.io/

**Comment by nonprofitable** [comment]
This is not an isolated issue with the logo / title; you should tackle this within the context of an overall redesign. You could do this while keeping the entire project in Jekyll, so you wouldn't lose the github hosting, though I'm curious as to how successfully you're getting folks to contribute links as Jekyll posts (I haven't had much luck with this with clients in the past).

**Comment by erichoog** [comment]
@nonprofitable I really liked the dsign of your page at https://nonprofitable.github.io
Do you have some suggestions or recommendations for us? I'm sure we would be open!

**Comment by nonprofitable** [comment]
Thanks! That code's all public (the public nonprofitable.org website is actually hosted from that github repo), so feel free to grab any ideas you like. You'll probably want to clean up the CSS a little if you're repurposing it. 

What do you like about it? The design / layout of the homepage and internal pages in general? I could probably build something similar for your project without too much pain.

Is there a slack / IRC channel for this somewhere? Let's do a quick chat about information architecture / design goals for the project, and I'll see if I can throw something together that your team likes. I've got some time I can volunteer in the near future.

**Comment by erichoog** [comment]
I'll certainly take a peak at some of the code for some inspiration!

I really like the overal design of your site, it just looks really clean.  Layout of the different sections, the style, the navbar, very easy on the eyes!

Our slack channel is https://mhwkb.slack.com/.  I have to run but I'm sure @andy5995 would love to see how you could help contribute the design as well.  Andy is the project owner so he may have some specific requirements or things he would like changed.  I might be on the channel later on though when I have some time so could possibly discuss then?   Thanks for responding back!

**Comment by andy5995** [comment]
nonprofitable:
>Is there a slack / IRC channel for this somewhere?

Mentioned a couple times in the README

>I could probably build something similar for your project without too much pain.

Hmm.. It's a nice design for sure, but I don't think it would fit well for a site such as ours.

Eric:
>Our slack channel is https://mhwkb.slack.com/. 

An invite link is required first, which can be obtained by using the link from the README.

**Comment by JedMeister** [comment]
my 2c (this is critique, but hopefully not too critical - please take it with a grain of salt): 

I think that the mhwkb site is coming along nicely. 

Although to my eye, the overall design reminds me a little of personal websites from the 90s. I think that the main thing that makes me think that is the background texture. Personally I think a plain background, or a picture (even if it was really blurry) would give it a more modern feel. No doubt @nonprofitable has more thoughts on that.

I'm also not 100% sure on the logo. It's quite nice, but it doesn't say "mental health and well-being" to me. I assume that the basis is the dharma wheel and I'm guessing that the stuff in the background of it are neurons. But at a glance, the background looks more like iridescent smoke or perhaps lightening. Whilst Buddhist practices may be consistent with positive mental health, the site isn't really about Buddism is it? So TBH, on face value, I don't think it's clear how the logo relates to the subject matter.

Having said that, I don't have any better logo suggestions so please feel free to ignore my feedback. :smile:

**Comment by andy5995** [comment]
>I'm also not 100% sure on the logo. It's quite nice, but it doesn't say "mental health and well-being" to me.

Thanks for the feedback. You made some good points, for sure. :)

I don't really know much about logo design. I figured a lot of logos don't necessarily represent the things they stand for. The Debian logo for instance, or...a penguin?? lol

The wheel can represent "balance" which is important for mental health.

Though me and @jamielthompson29 decided we could always change the logo later. And it's something to consider if a graphic designer ever comes along and make me a better offer. I'm quite happy with the logo actually, except I think I'd like something with lighter colors. I'm seeing too many dark colors in the web site theme.

>Having said that, I don't have any better logo suggestions so please feel free to ignore my feedback. 😄

Never! I'll never ignore your feedback @JedMeister ! :)

I'll keep it in mind as we continue. The first thing was getting at least a _basic_ design in place. As more people join, we'll have more options to make things sexier.

Everyone who thinks JedMeister gave valid feedback... give his post a "thumbs-up"!

**Comment by overdrv69** [comment]
andy5995, after reading through posts and looking at your site. I also like the simplicity of your design but with regards to the logo, might I suggest something more elemental. I have designed logos for home healthcare sites and find that visitors relate to symbols more that’s words.  Brainstorming an idea for the right logo can take time, I would start with word association to find the symbol that best describes what your service provides.  If you want more detail or help let me know.

**Comment by andy5995** [comment]
Hi @overdrv69 . I'm open to new ideas. :) Please join the [chat room](https://join.slack.com/t/mhwkb/shared_invite/enQtMjU3MjcwMTk4NjYzLTA0ZDc2YjAwMDJiNTU1YTBmYTViNmQ5MTdjOTk2MDA2MDMyMzNiYjU4ZWIzMTZlNmU4ZjFhNDg1MjQ5OGQyMjI) so we can explore them more. Thank you for the offer. :)

**Comment by overdrv69** [comment]
I have some ideas to share, working on them now.  I also commented on another Slack post about your menu options.

**Comment by andy5995** [comment]
I've decided to keep the logo. I like it, and have received many compliments about it (cc: @jamielthompson29 )

This thread is too long. I'm going to close it and create a new ticket after some of the current issues being worked on are resolved.
