### ISSUE TITLE
Move style attributes in some _includes files to a CSS class

### ISSUE THREAD

**Issue by erichoog** [mhwkb/mhwkb.github.io#76]
There is some CSS embedded into a few _includes files in style attributes which could be moved to a CSS class is the style.css file.

**Comment by andy5995** [comment]
https://github.com/mhwkb/mhwkb.github.io/blob/0eb79c75be8fb4abbd926f371738d5f641d0ed86/jekyll/_includes/footer.html#L17

Anywhere else, @erichoog ?

**Comment by erichoog** [comment]
@andy5995 I think there are about 4 lines in the footer.html.  and a couple in the post_display.html file as well.
