### ISSUE TITLE
Displaying RSS feeds

### ISSUE THREAD

**Issue by andy5995** [mhwkb/mhwkb.github.io#93]
Are there any good web services that provide a way to display RSS feeds on static web sites such as ours?

I thought it might be a nice addition to display about 4 RSS feeds; perhaps 5 headlines from each feed in the footre.

I haven't decided yet which feeds to display but we can discuss that soon.

**Comment by erichoog** [comment]
I think there's got to be some sort of JavaScript RSS reader that would work for this.

I'll take a look here https://www.sitepoint.com/jquery-rss-feed-readers/

Or maybe this project although I'm not sure it being maintained.  https://github.com/sdepold/jquery-rss

**Comment by escottalexander** [comment]
@andy5995 Where will this rss feed be located? Just on the home page or on all of the sites pages?

**Comment by andy5995** [comment]
Very good question! I think a separate page. And if so, there could be feeds from more than 4 sources.

I figure we'll work on the design issues, and then perhaps discuss the RSS thing more in Slack.

**Comment by erichoog** [comment]
I think this might be a great plugin for showing rss feeds: https://github.com/sdepold/jquery-rss

It has template settings which would be very helpful in our case.

**Comment by andy5995** [comment]
Thanks for investigating, Eric.

https://github.com/sdepold/jquery-rss#note-about-the-host-option
>Since version 3.0.0 the plugin is no longer using the Google Feed API but a drop-in replacement called feedr. That server is currently running on Heroku and might have some downtimes, interruptions or unexpected issues. While I will try to keep those problems as rare as possible, it can totally happen from time to time. I might move the service to some other provide or even improve the infrastructure.

>If you don't want to rely on the provided server and instead run your own version, you can just download feedr, install the dependencies and run it. As written above, you can specify the host which is used to parse the feeds with the host option.

I'd prefer a method that doesn't rely on a third-party service. Do you think that's possible with jquery? And would something ruby-based be an option?

Here's another option.. https://rss.bloople.net/
